import type { ReactNode } from 'react'
import { useTranslation } from 'react-i18next'
import { Button } from '@/components/ui/button'
import { translate } from '@/i18n/i18n'
import { selectConversationHistoryTarget } from '@/lib/conversation-history-selection'
import { useAppStore } from '@/store'
import type { ConversationKnowledgeItem } from '../../../../shared/conversation-knowledge-items'

export function ConversationKnowledgeDetail({
  item
}: {
  item: ConversationKnowledgeItem
}): React.JSX.Element {
  useTranslation()

  const openSourceHistory = (): void => {
    selectConversationHistoryTarget(item.source)
    const store = useAppStore.getState()
    store.setConversationKnowledgeDrawerOpen(false)
    store.setRightSidebarTab('vault')
    store.setRightSidebarOpen(true)
    const dispatchSelection = (): void => {
      window.dispatchEvent(new Event('orca:conversation-history-select'))
    }
    window.setTimeout(dispatchSelection, 0)
    window.setTimeout(dispatchSelection, 120)
  }

  return (
    <article className="space-y-4 p-4">
      <div>
        <h2 className="text-base font-medium">{item.knowledge.title ?? item.source.title}</h2>
        <p className="mt-1 text-xs text-muted-foreground">
          {translate(
            'conversationKnowledge.detail.generatedBy',
            'Generated by {{agent}} · {{model}}',
            { agent: item.generator.agent, model: item.generator.model }
          )}
        </p>
      </div>
      <DetailSection title={translate('conversationKnowledge.detail.summary', 'Summary')}>
        <p className="text-sm leading-6">{item.knowledge.summary}</p>
      </DetailSection>
      <DetailList
        title={translate('conversationKnowledge.detail.conclusions', 'Key conclusions')}
        values={item.knowledge.conclusions}
      />
      <DetailList
        title={translate('conversationKnowledge.detail.topics', 'Topics')}
        values={item.knowledge.topics}
        inline
      />
      <DetailList
        title={translate('conversationKnowledge.detail.entities', 'Entities')}
        values={item.knowledge.entities}
        inline
      />
      <DetailSection title={translate('conversationKnowledge.detail.source', 'Source')}>
        <p className="text-xs text-muted-foreground">
          {item.source.agent} · {item.source.sessionId}
        </p>
        <Button className="mt-2" size="sm" variant="outline" onClick={openSourceHistory}>
          {translate(
            'conversationKnowledge.detail.openSessionHistory',
            'Open Agent Session History'
          )}
        </Button>
      </DetailSection>
    </article>
  )
}

function DetailSection({
  title,
  children
}: {
  title: string
  children: ReactNode
}): React.JSX.Element {
  return (
    <section>
      <h3 className="mb-1.5 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
        {title}
      </h3>
      {children}
    </section>
  )
}

function DetailList({
  title,
  values,
  inline = false
}: {
  title: string
  values: string[]
  inline?: boolean
}): React.JSX.Element | null {
  if (!values.length) {
    return null
  }
  return (
    <DetailSection title={title}>
      <ul className={inline ? 'flex flex-wrap gap-1.5' : 'space-y-1.5'}>
        {values.map((value) => (
          <li
            key={value}
            className={
              inline
                ? 'rounded-md border border-border px-2 py-1 text-xs'
                : 'text-sm leading-5 before:mr-2 before:text-muted-foreground before:content-["•"]'
            }
          >
            {value}
          </li>
        ))}
      </ul>
    </DetailSection>
  )
}
